### ISSUE TITLE
Format not handled per step

### ISSUE THREAD

**Issue by felixbuenemann** [cloud8421/dragonfly-server#4]
While reading the step tests, I noticed that the format is stored globally instead of for each convert step. So if multiple processing steps are given, the format from the last step is used for all intermediate steps. This is not such a good idea if the format is lossy, like jpeg.

Maybe it would be better to store the format with every intermediate step or force a lossless format for intermediate steps.

In most cases this should be avoidable, because pretty much all transformations can be done in a single convert call.

One test that shows the problem:

``` elixir
  test "works with local files" do
    steps = [["ff", "/app/foo.jpg"],
             ["p", "convert", "-thumbnail 273x273^^ -gravity center -crop 273x273+0+0 +repage -draw 'polygon 0,0 273,273 273,0 fill none matte 135,135 floodfill'", "png"],
             ["p", "thumb", "892x320#"],
             ["e", "jpg"]]
    commands = %Steps{file: "/app/foo.jpg",
                convert: "#{Config.convert_command} -'[0]' -thumbnail 273x273^^ -gravity center -crop 273x273+0+0 +repage -draw 'polygon 0,0 273,273 273,0 fill none matte 135,135 floodfill' jpg:- | #{Config.convert_command} - -resize 892x320^^ -gravity center -crop 892x320+0+0 +repage -strip jpg:-",
                format: "jpg"}
    assert(commands == Steps.deserialize(steps))
  end
```

In the first processing step, png is specified as format, but the convert command used jpg instead.

**Comment by felixbuenemann** [comment]
All intermediate steps should probably use `miff:` format, which is lossless and can be piped.

**Comment by cloud8421** [comment]
`miff:` sounds good.

Regarding multiple steps transformations, they were frequent enough in the original deployment for this app, hence why they were supported from the beginning.

Thanks!

**Comment by felixbuenemann** [comment]
OK, I'll try to come up with a PR to change that. I'll have a busy week, so probably not before the upcoming weekend.
